import * as PreparationIds from 'src/constants/universal-identifiers';
import {
  defineObject,
  FieldType,
  OnDeleteAction,
  RelationType,
} from 'twenty-sdk/define';

import {
  FINANCE_FACT_AMOUNT_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_ARTIFACT_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_SOURCE_LOCATION_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_SOURCE_AMOUNT_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_SOURCE_SIGN_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_TRANSACTION_DATE_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_POSTED_DATE_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_RAW_VALUES_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_CLASSIFICATION_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_DESCRIPTION_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_EXCLUSION_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_INCLUDED_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_KEY_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_OBJECT_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_PERIOD_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_REVISION_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_SOURCE_ROW_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_KIND_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_SOURCE_NATIVE_ID_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_PROVIDER_LIFECYCLE_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_EFFECTIVE_AT_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_OBSERVED_AT_FIELD_UNIVERSAL_IDENTIFIER,
  FINANCE_FACT_NORMALIZATION_RULE_FIELD_UNIVERSAL_IDENTIFIER,
  SOURCE_ARTIFACT_OBJECT_UNIVERSAL_IDENTIFIER,
  SOURCE_ARTIFACT_FACTS_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

enum Classification {
  REVENUE = 'REVENUE',
  OPERATING_EXPENSE = 'OPERATING_EXPENSE',
  REFUND = 'REFUND',
  VOID = 'VOID',
  DISCOUNT = 'DISCOUNT',
  INTERNAL_TRANSFER = 'INTERNAL_TRANSFER',
  CARD_PAYMENT = 'CARD_PAYMENT',
  UNCLASSIFIED = 'UNCLASSIFIED',
}

enum FactStatus {
  POSTED = 'POSTED',
  PENDING = 'PENDING',
  SUPERSEDED = 'SUPERSEDED',
}

enum ProviderLifecycleState {
  PENDING = 'PENDING',
  POSTED = 'POSTED',
  REMOVED = 'REMOVED',
  REPLACED = 'REPLACED',
  SUPERSEDED = 'SUPERSEDED',
  SNAPSHOT_ONLY = 'SNAPSHOT_ONLY',
}

export default defineObject({
  universalIdentifier: FINANCE_FACT_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'financeFact',
  namePlural: 'financeFacts',
  labelSingular: 'Finance fact',
  labelPlural: 'Finance facts',
  description:
    'Normalized, revision-aware financial fact with bounded source lineage.',
  icon: 'IconCurrencyDollar',
  labelIdentifierFieldMetadataUniversalIdentifier:
    FINANCE_FACT_KEY_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier:
        PreparationIds.FINANCE_FACT_ACCOUNT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RELATION,
      name: 'financialAccount',
      label: 'Financial account',
      icon: 'IconBuildingBank',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier:
        PreparationIds.FINANCIAL_ACCOUNT_OBJECT_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier:
        PreparationIds.FINANCIAL_ACCOUNT_FACTS_FIELD_UNIVERSAL_IDENTIFIER,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'financialAccountId',
      },
    },
    {
      universalIdentifier:
        PreparationIds.FINANCE_FACT_MINOR_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'exactAmountMinor',
      label: 'Exact amount (minor units)',
      icon: 'IconCurrencyDollar',
      isNullable: true,
      description:
        'Canonical signed integer text, inflow-positive. Validate with the shared money contract before publication.',
    },
    {
      universalIdentifier:
        PreparationIds.FINANCE_FACT_CURRENCY_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'sourceCurrency',
      label: 'Source currency',
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    {
      universalIdentifier: FINANCE_FACT_KEY_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'factKey',
      label: 'Fact key',
      icon: 'IconKey',
    },
    {
      universalIdentifier: FINANCE_FACT_SOURCE_ROW_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'sourceRowKey',
      label: 'Source row key',
      icon: 'IconTable',
    },
    {
      universalIdentifier:
        FINANCE_FACT_SOURCE_LOCATION_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'sourceLocation',
      label: 'Source location',
      description: 'Exact file row or source record location.',
      icon: 'IconMapPin',
    },
    {
      universalIdentifier:
        FINANCE_FACT_SOURCE_AMOUNT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'sourceAmount',
      label: 'Original source amount',
      icon: 'IconReceipt',
    },
    {
      universalIdentifier: FINANCE_FACT_SOURCE_SIGN_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'sourceSignConvention',
      label: 'Source sign convention',
      icon: 'IconArrowsExchange',
    },
    {
      universalIdentifier:
        FINANCE_FACT_TRANSACTION_DATE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'transactionDate',
      label: 'Transaction date',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: FINANCE_FACT_POSTED_DATE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'postedDate',
      label: 'Posted date',
      icon: 'IconCalendarCheck',
      isNullable: true,
    },
    {
      universalIdentifier: FINANCE_FACT_RAW_VALUES_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'rawValues',
      label: 'Unmodified source values',
      icon: 'IconBraces',
    },
    {
      universalIdentifier: FINANCE_FACT_ARTIFACT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RELATION,
      name: 'artifact',
      label: 'Source artifact',
      icon: 'IconFileDescription',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier:
        SOURCE_ARTIFACT_OBJECT_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier:
        SOURCE_ARTIFACT_FACTS_FIELD_UNIVERSAL_IDENTIFIER,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'artifactId',
      },
    },
    {
      universalIdentifier: FINANCE_FACT_PERIOD_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'period',
      label: 'Period',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: FINANCE_FACT_AMOUNT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.CURRENCY,
      name: 'amount',
      label: 'Amount (USD)',
      icon: 'IconCurrencyDollar',
    },
    {
      universalIdentifier:
        FINANCE_FACT_CLASSIFICATION_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'classification',
      label: 'Classification',
      icon: 'IconCategory',
      options: [
        {
          id: 'e9e1d2f3-a4b5-4678-9012-3456789abd01',
          value: Classification.REVENUE,
          label: 'Revenue',
          color: 'green',
          position: 0,
        },
        {
          id: 'e9e1d2f3-a4b5-4678-9012-3456789abd02',
          value: Classification.OPERATING_EXPENSE,
          label: 'Operating expense',
          color: 'red',
          position: 1,
        },
        {
          id: 'e9e1d2f3-a4b5-4678-9012-3456789abd03',
          value: Classification.REFUND,
          label: 'Refund',
          color: 'orange',
          position: 2,
        },
        {
          id: 'e9e1d2f3-a4b5-4678-9012-3456789abd04',
          value: Classification.VOID,
          label: 'Void',
          color: 'gray',
          position: 3,
        },
        {
          id: 'e9e1d2f3-a4b5-4678-9012-3456789abd05',
          value: Classification.DISCOUNT,
          label: 'Discount',
          color: 'yellow',
          position: 4,
        },
        {
          id: 'e9e1d2f3-a4b5-4678-9012-3456789abd06',
          value: Classification.INTERNAL_TRANSFER,
          label: 'Internal transfer',
          color: 'purple',
          position: 5,
        },
        {
          id: 'e9e1d2f3-a4b5-4678-9012-3456789abd07',
          value: Classification.CARD_PAYMENT,
          label: 'Card payment',
          color: 'blue',
          position: 6,
        },
        {
          id: 'e9e1d2f3-a4b5-4678-9012-3456789abd10',
          value: Classification.UNCLASSIFIED,
          label: 'Unclassified source row',
          color: 'gray',
          position: 7,
        },
      ],
    },
    {
      universalIdentifier: FINANCE_FACT_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      icon: 'IconProgress',
      options: [
        {
          id: 'e9e1d2f3-a4b5-4678-9012-3456789abd08',
          value: FactStatus.POSTED,
          label: 'Posted',
          color: 'green',
          position: 0,
        },
        {
          id: 'e9e1d2f3-a4b5-4678-9012-3456789abd09',
          value: FactStatus.PENDING,
          label: 'Pending',
          color: 'yellow',
          position: 1,
        },
        {
          id: 'e9e1d2f3-a4b5-4678-9012-3456789abda0',
          value: FactStatus.SUPERSEDED,
          label: 'Superseded',
          color: 'gray',
          position: 2,
        },
      ],
    },
    {
      universalIdentifier: FINANCE_FACT_REVISION_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'revision',
      label: 'Revision',
      icon: 'IconVersions',
    },
    {
      universalIdentifier: FINANCE_FACT_INCLUDED_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.BOOLEAN,
      name: 'includedInTotals',
      label: 'Included in totals',
      icon: 'IconCalculator',
    },
    {
      universalIdentifier: FINANCE_FACT_EXCLUSION_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'exclusionReason',
      label: 'Exclusion reason',
      icon: 'IconFilterOff',
      isNullable: true,
    },
    {
      universalIdentifier: FINANCE_FACT_DESCRIPTION_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'description',
      label: 'Description',
      icon: 'IconNotes',
    },
    {
      universalIdentifier: FINANCE_FACT_KIND_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'factKind',
      label: 'Fact kind',
      description: 'Bank movement, sale, tender, fee, reserve, payout or other normalized component.',
      icon: 'IconCategory',
      isNullable: true,
    },
    {
      universalIdentifier: FINANCE_FACT_SOURCE_NATIVE_ID_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'sourceNativeId',
      label: 'Source native ID',
      icon: 'IconId',
      isNullable: true,
    },
    {
      universalIdentifier: FINANCE_FACT_PROVIDER_LIFECYCLE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'providerLifecycleState',
      label: 'Provider lifecycle',
      icon: 'IconTimelineEvent',
      isNullable: true,
      options: [
        { id: 'abfe1172-f6d9-4253-bd85-9d7cfdcd10d1', value: ProviderLifecycleState.PENDING, label: 'Pending', color: 'yellow', position: 0 },
        { id: '9628166d-63d2-48a9-8856-04a5be7922ce', value: ProviderLifecycleState.POSTED, label: 'Posted', color: 'green', position: 1 },
        { id: '2d5f89b9-ff1c-492c-8a7f-ff6d0f62c432', value: ProviderLifecycleState.REMOVED, label: 'Removed', color: 'red', position: 2 },
        { id: '97e88382-4f41-42c6-a9df-958a8c454687', value: ProviderLifecycleState.REPLACED, label: 'Replaced', color: 'blue', position: 3 },
        { id: 'c16e58a4-13bb-4272-9a7f-d6d7300e8313', value: ProviderLifecycleState.SUPERSEDED, label: 'Superseded', color: 'gray', position: 4 },
        { id: '6bfdd777-e26b-44e1-93be-2f6ef2100dd1', value: ProviderLifecycleState.SNAPSHOT_ONLY, label: 'Snapshot only', color: 'purple', position: 5 },
      ],
    },
    {
      universalIdentifier: FINANCE_FACT_EFFECTIVE_AT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'effectiveAt',
      label: 'Effective at',
      icon: 'IconCalendarTime',
      isNullable: true,
    },
    {
      universalIdentifier: FINANCE_FACT_OBSERVED_AT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'observedAt',
      label: 'Observed at',
      icon: 'IconClock',
      isNullable: true,
    },
    {
      universalIdentifier: FINANCE_FACT_NORMALIZATION_RULE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'normalizationRuleVersion',
      label: 'Normalization rule',
      icon: 'IconVersions',
      isNullable: true,
    },
  ],
});
