import {
  defineObject,
  FieldType,
  MetadataWritability,
  RelationType,
  OnDeleteAction,
} from 'twenty-sdk/define';
import {
  PAYMENT_REVISION_OBJECT,
  PAYMENT_CONNECTION_FIELD,
  CONNECTION_PAYMENTS_FIELD,
  CONNECTION_OBJECT,
} from '../contracts/model-identifiers';
export default defineObject({
  universalIdentifier: PAYMENT_REVISION_OBJECT,
  nameSingular: 'cloverPaymentRevision',
  namePlural: 'cloverPaymentRevisions',
  labelSingular: 'Clover payment revision',
  labelPlural: 'Clover payment revisions',
  icon: 'IconReceipt',
  writability: MetadataWritability.APPLICATION,
  isUICreatable: false,
  isUIEditable: false,
  fields: [
    {
      universalIdentifier: 'bce870fe-d90d-458f-b33b-195e5856216f',
      name: 'revisionKey',
      label: 'revisionKey',
      type: FieldType.TEXT,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: '54241718-5a81-4c37-acce-4b4dfd51d61b',
      name: 'sourceKey',
      label: 'sourceKey',
      type: FieldType.TEXT,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: '04eacb72-57b2-4d79-850e-bf8127f8c5ee',
      name: 'paymentId',
      label: 'paymentId',
      type: FieldType.TEXT,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: '314d0de9-1fe4-4834-a6e9-5306c2b8eab6',
      name: 'merchantId',
      label: 'merchantId',
      type: FieldType.TEXT,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: 'ed9ce8ce-3053-438e-9ce1-74fae7a4f17b',
      name: 'amountMinor',
      label: 'amountMinor',
      type: FieldType.NUMBER,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: '56c44aab-824f-42e3-8f47-4933fa8984c1',
      name: 'currencyCode',
      label: 'Currency code',
      type: FieldType.TEXT,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: '6e5be263-1594-4ac0-be29-8fe729f14144',
      name: 'createdTimeMs',
      label: 'createdTimeMs',
      type: FieldType.NUMBER,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: '911a5e53-3268-4592-8ec6-a691a822d2e3',
      name: 'modifiedTimeMs',
      label: 'modifiedTimeMs',
      type: FieldType.NUMBER,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: 'c84788d3-739c-4f70-99db-75641de31ca1',
      name: 'result',
      label: 'result',
      type: FieldType.TEXT,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: '94e2dbf4-5a1e-44dc-adae-23cc82f692e0',
      name: 'voided',
      label: 'voided',
      type: FieldType.BOOLEAN,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: '1b5d011e-90f9-48c9-b306-965cd35b3ca3',
      name: 'observedAt',
      label: 'observedAt',
      type: FieldType.DATE_TIME,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: PAYMENT_CONNECTION_FIELD,
      name: 'connection',
      label: 'Connection',
      type: FieldType.RELATION,
      icon: 'IconLink',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: CONNECTION_OBJECT,
      relationTargetFieldMetadataUniversalIdentifier: CONNECTION_PAYMENTS_FIELD,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.RESTRICT,
        joinColumnName: 'connectionId',
      },
    },
  ],
});
