import {
  defineObject,
  FieldType,
  MetadataWritability,
  RelationType,
  OnDeleteAction,
} from 'twenty-sdk/define';
import {
  IMPORT_RECEIPT_OBJECT,
  RECEIPT_CONNECTION_FIELD,
  CONNECTION_RECEIPTS_FIELD,
  CONNECTION_OBJECT,
} from '../contracts/model-identifiers';
export default defineObject({
  universalIdentifier: IMPORT_RECEIPT_OBJECT,
  nameSingular: 'cloverImportReceipt',
  namePlural: 'cloverImportReceipts',
  labelSingular: 'Clover import receipt',
  labelPlural: 'Clover import receipts',
  icon: 'IconReceipt',
  writability: MetadataWritability.APPLICATION,
  isUICreatable: false,
  isUIEditable: false,
  fields: [
    {
      universalIdentifier: '1b5dc9e9-2030-45c5-ae08-76976e53953b',
      name: 'pageKey',
      label: 'pageKey',
      type: FieldType.TEXT,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: 'f1f3c7ed-4797-4779-9885-b4caf82a1c87',
      name: 'requestKey',
      label: 'requestKey',
      type: FieldType.TEXT,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: '7387540a-abac-4aad-be07-b1803f2854ca',
      name: 'dataset',
      label: 'dataset',
      type: FieldType.TEXT,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: 'e8193e1d-f88b-4855-b2fd-281b7cee906d',
      name: 'grantId',
      label: 'grantId',
      type: FieldType.UUID,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: '3da79dea-cd2c-49b2-9b85-98ed4620e3d4',
      name: 'fromMs',
      label: 'fromMs',
      type: FieldType.NUMBER,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: '9033c560-cd11-4595-b128-3e32ba58a62d',
      name: 'toMs',
      label: 'toMs',
      type: FieldType.NUMBER,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: 'c2e8bc54-12f3-45fe-be3f-6d3ea339bca4',
      name: 'timeField',
      label: 'timeField',
      type: FieldType.TEXT,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: '64e2b35b-e0a5-40be-aada-7e51d3f3db8d',
      name: 'offset',
      label: 'offset',
      type: FieldType.NUMBER,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: '0231d5f3-7a86-4744-86e5-bead6014d1ec',
      name: 'nextOffset',
      label: 'nextOffset',
      type: FieldType.NUMBER,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: 'd8312f92-3e42-4ee4-a629-5ebdbf57a8dd',
      name: 'rowCount',
      label: 'rowCount',
      type: FieldType.NUMBER,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: 'bf25c2f4-3aa6-413f-91d8-dc35dde1f66e',
      name: 'revisionKeys',
      label: 'revisionKeys',
      type: FieldType.RAW_JSON,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: '1f3bc34d-3276-4a15-9dcb-754b258121b8',
      name: 'observedAt',
      label: 'observedAt',
      type: FieldType.DATE_TIME,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: '8e4e6f68-e70a-4310-ad74-9d3665b969dd',
      name: 'coverage',
      label: 'coverage',
      type: FieldType.TEXT,
      icon: 'IconInfoCircle',
    },
    {
      universalIdentifier: RECEIPT_CONNECTION_FIELD,
      name: 'connection',
      label: 'Connection',
      type: FieldType.RELATION,
      icon: 'IconLink',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier: CONNECTION_OBJECT,
      relationTargetFieldMetadataUniversalIdentifier: CONNECTION_RECEIPTS_FIELD,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.RESTRICT,
        joinColumnName: 'connectionId',
      },
    },
  ],
});
