#!/usr/bin/env python3
"""Generate the browser-safe legal source module from verified Markdown."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


PACKET_DIRECTORY = Path("docs/legal/mhoo/v2.0")
OUTPUT_PATH = Path(
    "packages/twenty-front/src/pages/legal/legal-document-sources.generated.ts",
)
DOCUMENTS = (
    ("terms", "01-mhoo-master-terms-v2.0.md"),
    ("privacy", "02-mhoo-privacy-policy-v2.0.md"),
    ("acceptableUse", "03-mhoo-acceptable-use-policy-v2.0.md"),
    ("openSource", "04-mhoo-open-source-notice-v2.0.md"),
    ("dpaAvailabilityNotice", "05-mhoo-dpa-availability-notice-v2.0.md"),
)


def render_generated_module(repository_root: Path) -> str:
    entries: list[str] = []
    for key, filename in DOCUMENTS:
        data = (repository_root / PACKET_DIRECTORY / filename).read_bytes()
        source = data.decode("utf-8")
        digest = hashlib.sha256(data).hexdigest()
        entries.append(
            f"  {key}: {{\n"
            f"    sourcePath: {json.dumps((PACKET_DIRECTORY / filename).as_posix())},\n"
            f"    sha256: {json.dumps(digest)},\n"
            f"    source: {json.dumps(source, ensure_ascii=False)},\n"
            "  },"
        )

    return (
        "// Generated by scripts/legal/generate_mhoo_legal_sources.py. Do not edit.\n"
        "export const MHO_LEGAL_DOCUMENT_SOURCES = {\n"
        + "\n".join(entries)
        + "\n} as const;\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    expected = render_generated_module(root)
    output = root / OUTPUT_PATH

    if args.write:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(expected, encoding="utf-8", newline="\n")
        print(f"wrote {OUTPUT_PATH}")
        return 0

    if not output.is_file() or output.read_text(encoding="utf-8") != expected:
        print(
            "MHO-226 generated legal sources are stale; run "
            "python3 scripts/legal/generate_mhoo_legal_sources.py --write",
        )
        return 1

    print("MHO-226 generated legal sources are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
