import styled from '@emotion/styled';
import { financeInsightsPrimitiveStyles, financeInsightsResponsiveStyles, financeInsightsTokens } from './finance-insights-styles';

// Page-specific layouts; shared Overview primitives own their visual styles.
export const Workspace = styled.section({
  '--fw-canvas': financeInsightsTokens.canvas,
  '--fw-surface': financeInsightsTokens.canvas,
  '--fw-nav': '#fafaff',
  '--fw-text': financeInsightsTokens.ink,
  '--fw-muted': financeInsightsTokens.muted,
  '--fw-line': financeInsightsTokens.line,
  '--fw-accent': financeInsightsTokens.selectionLabel,
  '--fw-soft': '#f1f1ff',
  '--fw-warn': 'var(--t-color-orange9)',
  '--fw-warn-bg': 'var(--t-background-transparent-orange)',
  '--fw-success': 'var(--t-color-green9)',
  color: 'var(--fw-text)',
  background: 'var(--fw-surface)',
  border: '1px solid var(--fw-line)',
  borderRadius: financeInsightsTokens.frameRadius,
  overflow: 'hidden',
  minHeight: '640px',
  width: 'min(100%, 1450px)',
  margin: '18px auto',
  position: 'relative',
  isolation: 'isolate',
  fontFamily: financeInsightsTokens.fontFamily,
  fontSize: '14px',
  lineHeight: 1.5,
  boxSizing: 'border-box',
  '& *': { boxSizing: 'border-box' },
  '& .fw-select, & .fi-search-input': { font: 'inherit' },
  '& button:disabled': { cursor: 'default', opacity: 0.5 },
  '& button:focus-visible, & select:focus-visible, & input:focus-visible, & summary:focus-visible':
    {
      outline:
        '3px solid color-mix(in srgb, var(--fw-accent) 42%, transparent)',
      outlineOffset: '2px',
    },
  '.dark &': {
    '--fw-canvas': 'var(--t-background-primary)',
    '--fw-surface': 'var(--t-background-primary)',
    '--fw-nav': 'var(--t-background-secondary)',
    '--fw-text': 'var(--t-font-color-primary)',
    '--fw-muted': 'var(--t-font-color-secondary)',
    '--fw-line': 'var(--t-border-color-light)',
    '--fw-soft': 'var(--t-background-transparent-blue)',
  },
  '& .fw-table-action': {
    border: 0,
    padding: 0,
    color: 'var(--fw-text)',
    background: 'transparent',
    cursor: 'pointer',
    fontWeight: 650,
    textAlign: 'left',
  },
  '& .fw-table-action:hover': { color: 'var(--fw-accent)' },
  '& .fw-chrome': {
    minHeight: '54px',
    display: 'flex',
    alignItems: 'center',
    gap: '13px',
    padding: '10px 18px',
    background: 'var(--fw-surface)',
    borderBottom: '1px solid var(--fw-line)',
  },
  '& .fw-logo': {
    color: 'var(--fw-accent)',
    fontSize: '22px',
    fontWeight: 750,
    letterSpacing: '-1.1px',
  },
  '& .fw-divider': {
    width: '1px',
    height: '19px',
    background: 'var(--fw-line)',
  },
  '& .fw-product': { fontSize: '12px', fontWeight: 650 },
  '& .fw-demo': {
    marginLeft: 'auto',
    border: '1px solid var(--fw-line)',
    borderRadius: '5px',
    padding: '4px 8px',
    color: 'var(--fw-muted)',
    fontSize: '10px',
    letterSpacing: '.2px',
  },
  '& .fw-layout': {
    display: 'grid',
    gridTemplateColumns: '166px minmax(0, 1fr)',
  },
  '& .fw-nav': {
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    padding: '22px 10px',
    background: 'var(--fw-nav)',
    borderRight: '1px solid var(--fw-line)',
  },
  '& .fw-nav-label': {
    margin: '2px 11px 11px',
    color: 'var(--fw-muted)',
    fontSize: '9px',
    fontWeight: 650,
    letterSpacing: '1px',
    textTransform: 'uppercase',
  },
  '& .fw-nav-button': {
    minHeight: '39px',
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: '9px',
    padding: '9px 11px',
    border: 0,
    borderRadius: '6px',
    color: 'var(--fw-text)',
    background: 'transparent',
    cursor: 'pointer',
    textAlign: 'left',
    fontSize: '11px',
  },
  '& .fw-nav-button:hover': { background: 'var(--fw-surface)' },
  '& .fw-nav-button[aria-current="page"]': {
    color: 'var(--fw-accent)',
    background: 'var(--fw-surface)',
    boxShadow: 'var(--t-box-shadow-light)',
  },
  '& .fw-nav-glyph': { width: '15px', textAlign: 'center', fontSize: '14px' },
  '& .fw-nav-meta': {
    margin: '28px 11px 0',
    color: 'var(--fw-muted)',
    fontSize: '9px',
    lineHeight: 1.55,
  },
  '& .fw-main': { minWidth: 0, padding: '27px 30px 28px' },
  '& .fw-title': {
    margin: 0,
    color: 'var(--fw-text)',
    fontSize: '26px',
    fontWeight: 520,
    letterSpacing: '-.8px',
    lineHeight: 1.2,
  },
  '& .fw-date-popover': {
    position: 'absolute',
    zIndex: 2,
    top: '39px',
    left: 0,
    minWidth: 'min(320px, calc(100vw - 48px))',
    maxWidth: 'calc(100vw - 48px)',
    padding: '13px',
    border: '1px solid var(--fw-line)',
    borderRadius: '9px',
    background: 'var(--fw-surface)',
    boxShadow: '0 10px 30px rgba(32, 33, 58, .10)',
  },
  '& .fw-select': {
    maxWidth: '190px',
    border: '1px solid var(--fw-line)',
    borderRadius: '6px',
    padding: '7px 9px',
    color: 'var(--fw-text)',
    background: 'var(--fw-surface)',
    fontSize: '11px',
  },
  '& .fw-metrics': {
    display: 'grid',
    gridTemplateColumns: '1.25fr 1fr 1fr',
    gap: '18px',
    padding: '17px 0 20px',
    borderTop: '1px solid var(--fw-line)',
    borderBottom: '1px solid var(--fw-line)',
  },
  '& .fw-label': { color: 'var(--fw-muted)', fontSize: '10px' },
  '& .fw-value': {
    margin: '4px 0 2px',
    fontSize: '30px',
    fontWeight: 560,
    letterSpacing: '-1px',
    lineHeight: 1.25,
    fontVariantNumeric: 'tabular-nums',
  },
  '& .fw-value small': {
    color: 'var(--fw-muted)',
    fontSize: '14px',
    fontWeight: 450,
    letterSpacing: 0,
  },
  '& .fw-sub': { color: 'var(--fw-muted)', fontSize: '9px' },
  '& .fw-warning': { color: 'var(--fw-warn)' },
  '& .fw-overview': {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.45fr) minmax(240px, 1fr)',
    gap: '24px',
    padding: '21px 0',
    borderBottom: '1px solid var(--fw-line)',
  },
  '& .fw-section-head': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '10px',
    marginBottom: '14px',
  },
  '& .fw-heading': { margin: 0, fontSize: '13px', fontWeight: 600 },
  '& .fw-mini': {
    border: '1px solid var(--fw-line)',
    borderRadius: '4px',
    padding: '3px 6px',
    color: 'var(--fw-muted)',
    fontSize: '9px',
  },
  '& .fw-chart': {
    height: '158px',
    display: 'grid',
    gridTemplateColumns: '32px repeat(2, minmax(75px, 1fr))',
    gap: '16px',
    paddingTop: '4px',
  },
  '& .fw-axis': {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    padding: '11px 0 25px',
    color: 'var(--fw-muted)',
    fontSize: '9px',
    textAlign: 'right',
  },
  '& .fw-month': {
    height: '100%',
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-end',
    padding: '0 10px',
    border: 0,
    borderRadius: '5px',
    color: 'var(--fw-text)',
    background: 'transparent',
    cursor: 'pointer',
  },
  '& .fw-month:hover, & .fw-month[aria-pressed="true"]': {
    background: 'var(--fw-soft)',
  },
  '& .fw-month-value': {
    marginBottom: '6px',
    fontSize: '11px',
    fontWeight: 600,
  },
  '& .fw-column': {
    width: '72%',
    maxWidth: '92px',
    minHeight: '2px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    overflow: 'hidden',
    borderRadius: '4px 4px 0 0',
    background: 'var(--fw-accent)',
    transition: 'height 180ms ease',
  },
  '& .fw-segment': {
    display: 'block',
    width: '100%',
    minHeight: '1px',
    borderBottom: '1px solid var(--fw-surface)',
  },
  '& .fw-segment:nth-of-type(even)': { opacity: 0.72 },
  '& .fw-segment[data-missing="true"]': {
    opacity: 1,
    background: 'var(--fw-warn-bg)',
  },
  '& .fw-month-label': {
    paddingTop: '7px',
    color: 'var(--fw-muted)',
    fontSize: '9px',
  },
  '& .fw-chart-key': {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    marginTop: '12px',
    color: 'var(--fw-muted)',
    fontSize: '9px',
  },
  '& .fw-hatch': {
    width: '12px',
    height: '8px',
    border: '1px solid var(--fw-warn)',
    background: 'var(--fw-warn-bg)',
  },
  '& .fw-insight': {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: '7px',
    marginTop: '13px',
    padding: '10px 11px',
    border: 0,
    borderRadius: '6px',
    color: 'var(--fw-accent)',
    background: 'var(--fw-soft)',
    cursor: 'pointer',
    textAlign: 'left',
    fontSize: '10px',
  },
  '& .fw-attention': {
    paddingLeft: '22px',
    borderLeft: '1px solid var(--fw-line)',
  },
  '& .fw-queue': { display: 'grid' },
  '& .fw-queue-row': {
    width: '100%',
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    gap: '4px 8px',
    padding: '11px 0',
    border: 0,
    borderTop: '1px solid var(--fw-line)',
    color: 'var(--fw-text)',
    background: 'transparent',
    cursor: 'pointer',
    textAlign: 'left',
  },
  '& .fw-queue-row:hover': { color: 'var(--fw-accent)' },
  '& .fw-queue-title': { minWidth: 0, fontSize: '10px', fontWeight: 600 },
  '& .fw-amount': { whiteSpace: 'nowrap', fontVariantNumeric: 'tabular-nums' },
  '& .fw-queue-reason': {
    gridColumn: '1 / -1',
    color: 'var(--fw-warn)',
    fontSize: '9px',
  },
  '& .fw-queue-foot': {
    paddingTop: '9px',
    color: 'var(--fw-muted)',
    fontSize: '9px',
  },
  '& .fw-table-head': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    padding: '17px 0 10px',
  },
  '& .fw-link': {
    padding: '4px',
    border: 0,
    color: 'var(--fw-accent)',
    background: 'transparent',
    cursor: 'pointer',
    fontSize: '9px',
  },
  '& .fw-table-wrap': { minWidth: 0, overflowX: 'auto' },
  '& .fw-table': {
    width: '100%',
    borderCollapse: 'collapse',
    tableLayout: 'fixed',
    background: 'var(--fw-surface)',
    fontSize: '10px',
  },
  '& .fw-table th': {
    padding: '8px 9px',
    borderTop: '1px solid var(--fw-line)',
    borderBottom: '1px solid var(--fw-line)',
    color: 'var(--fw-muted)',
    background: 'var(--fw-nav)',
    fontSize: '9px',
    fontWeight: 550,
    textAlign: 'left',
  },
  '& .fw-table td': {
    height: '42px',
    padding: '8px 9px',
    borderBottom: '1px solid var(--fw-line)',
    verticalAlign: 'middle',
    overflowWrap: 'anywhere',
  },
  '& .fw-statement-table': { minWidth: '960px', tableLayout: 'auto' },
  '& .fw-statement-table .fw-money-col': { width: 'auto' },
  '& .fw-statement-table .fw-control-value': {
    whiteSpace: 'nowrap',
    fontVariantNumeric: 'tabular-nums',
  },
  '& .fw-table tbody tr[tabindex]': { cursor: 'pointer' },
  '& .fw-table tbody tr[tabindex]:hover td': {
    background: 'var(--fw-soft)',
  },
  '& .fw-check-col': { width: '34px' },
  '& .fw-date-col': { width: '13%' },
  '& .fw-account-col': { width: '16%' },
  '& .fw-evidence-col': { width: '19%' },
  '& .fw-money-col': { width: '14%', textAlign: 'right' },
  '& .fw-checkbox': {
    width: '14px',
    height: '14px',
    display: 'inline-block',
    border: '1px solid var(--fw-line)',
    borderRadius: '3px',
    background: 'var(--fw-surface)',
  },
  '& .fw-status': {
    display: 'inline-flex',
    padding: '3px 6px',
    borderRadius: '4px',
    color: 'var(--fw-muted)',
    background: 'var(--fw-nav)',
    fontSize: '8px',
    lineHeight: 1.35,
  },
  '& .fw-status[data-tone="warn"]': {
    color: 'var(--fw-warn)',
    background: 'var(--fw-warn-bg)',
  },
  '& .fw-actions': {
    display: 'flex',
    alignItems: 'center',
    gap: '7px',
    marginBottom: '13px',
  },
  '& .fw-button': {
    minHeight: '33px',
    padding: '7px 10px',
    border: '1px solid var(--fw-line)',
    borderRadius: '6px',
    color: 'var(--fw-text)',
    background: 'var(--fw-surface)',
    cursor: 'pointer',
    fontSize: '10px',
    fontWeight: 550,
    whiteSpace: 'nowrap',
  },
  '& .fw-button:hover': { background: 'var(--fw-soft)' },
  '& .fw-button[aria-pressed="true"]': {
    color: 'var(--fw-accent)',
    borderColor: 'var(--fw-accent)',
  },
  '& .fw-primary': {
    color: 'var(--t-font-color-inverted)',
    borderColor: 'var(--fw-accent)',
    background: 'var(--fw-accent)',
  },
  '& .fw-primary:hover': {
    filter: 'brightness(.96)',
    background: 'var(--fw-accent)',
  },
  '& .fw-account-picker': { marginLeft: 'auto', minWidth: '240px' },
  '& .fw-page-note': {
    margin: '-8px 0 17px',
    color: 'var(--fw-muted)',
    fontSize: '10px',
  },
  '& .fw-panels': {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '12px',
  },
  '& .fw-panel': {
    minWidth: 0,
    padding: '16px',
    border: '1px solid var(--fw-line)',
    borderRadius: '7px',
    background: 'var(--fw-surface)',
  },
  '& .fw-panel-top': {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '10px',
    alignItems: 'flex-start',
    marginBottom: '13px',
  },
  '& .fw-panel-title': { margin: 0, fontSize: '12px', fontWeight: 600 },
  '& .fw-definition': {
    display: 'grid',
    gridTemplateColumns: '100px minmax(0, 1fr)',
    gap: '8px 12px',
    margin: 0,
    paddingTop: '12px',
    borderTop: '1px solid var(--fw-line)',
    fontSize: '10px',
  },
  '& .fw-definition dt': { color: 'var(--fw-muted)' },
  '& .fw-definition dd': { margin: 0 },
  '& .fw-empty': {
    padding: '38px 16px',
    color: 'var(--fw-muted)',
    textAlign: 'center',
    fontSize: '11px',
  },
  '& .fw-bottom': {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '12px',
    alignItems: 'center',
    paddingTop: '15px',
    color: 'var(--fw-muted)',
    fontSize: '8px',
  },
  '& .fw-details': {
    marginTop: '13px',
    paddingTop: '11px',
    borderTop: '1px solid var(--fw-line)',
    color: 'var(--fw-muted)',
    fontSize: '9px',
  },
  '& .fw-details summary': { cursor: 'pointer', fontWeight: 600 },
  '& .fw-details p': { margin: '8px 0 0', lineHeight: 1.55 },
  '& .fw-insights-layout': {
    display: 'grid',
    gridTemplateColumns: '28% minmax(0, 1fr)',
    gap: '0',
    padding: '29px 0 20px',
    borderBottom: '1px solid var(--fw-line)',
    minWidth: 0,
  },
  '& .fw-narrative-panel': {
    minWidth: 0,
    paddingRight: '28px',
    borderRight: '1px solid var(--fw-line)',
  },
  '& .fw-selected-money': {
    margin: '4px 0 5px',
    fontSize: '34px',
    fontWeight: 520,
    letterSpacing: '-1.1px',
    lineHeight: 1.25,
    fontVariantNumeric: 'tabular-nums',
  },
  '& .fw-recap': { display: 'grid', gap: '17px', marginTop: '27px' },
  '& .fw-recap-button': {
    width: '100%',
    display: 'grid',
    gridTemplateColumns: '13px minmax(0, 1fr)',
    gap: '7px',
    padding: 0,
    border: 0,
    color: 'var(--fw-text)',
    background: 'transparent',
    cursor: 'pointer',
    textAlign: 'left',
    fontSize: '10px',
    lineHeight: 1.5,
  },
  '& .fw-recap-button strong': {
    display: 'block',
    marginBottom: '3px',
    fontWeight: 600,
  },
  '& .fw-chart-stats': {
    display: 'flex',
    gap: '28px',
    flexWrap: 'wrap',
    marginBottom: '14px',
  },
  '& .fw-chart-stat strong': {
    display: 'block',
    marginTop: '3px',
    fontSize: '17px',
    fontWeight: 520,
  },
  '& .fw-line-chart': {
    display: 'block',
    width: '100%',
    height: '250px',
    overflow: 'visible',
  },
  '& .fw-line-chart text': {
    fill: 'var(--fw-muted)',
    fontFamily: 'var(--t-font-family)',
    fontSize: '11px',
  },
  '& .fw-line-chart-grid': {
    stroke: 'var(--fw-line)',
    strokeWidth: 1,
    strokeDasharray: '2 4',
  },
  '& .fw-line-chart-path': {
    fill: 'none',
    stroke: 'var(--fw-accent)',
    strokeWidth: 2.2,
  },
  '& .fw-line-chart-path[data-direction="in"]': {
    stroke: 'var(--fw-success)',
  },
  '& .fw-line-chart-dot': {
    fill: 'var(--fw-accent)',
    stroke: 'var(--fw-surface)',
    strokeWidth: 2,
  },
  '& .fw-line-chart-dot[data-direction="in"]': {
    fill: 'var(--fw-success)',
  },
  '& .fw-movement-hero': {
    margin: 0,
    padding: '0 0 0 30px',
    background: 'transparent',
  },
  '& .fw-movement-head': {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '18px',
    marginBottom: '14px',
  },
  '& .fw-movement-head .fw-heading': {
    marginBottom: '4px',
    fontSize: '16px',
    letterSpacing: '-.01em',
  },
  '& .fw-overlay-chart': {
    display: 'block',
    width: '100%',
    height: 'auto',
    overflow: 'visible',
  },
  '& .fw-chart-viewport': { overflowX: 'auto', overscrollBehaviorInline: 'contain' },
  '& .fw-overlay-chart text': {
    fill: 'var(--fw-muted)',
    fontFamily: 'var(--t-font-family)',
    fontSize: '12px',
  },
  '& .fw-chart-grid': {
    stroke: 'color-mix(in srgb, var(--fw-line) 65%, transparent)',
    strokeWidth: 1,
  },
  '& .fw-chart-zero': { stroke: 'var(--fw-muted)', strokeWidth: 1, strokeDasharray: '4 5', opacity: .55 },
  '& .fw-chart-candle': { opacity: .22, pointerEvents: 'none' },
  '& .fw-chart-candle-wick': { strokeWidth: 2 },
  '& .fw-chart-candle-body': { strokeWidth: 1.5 },
  '& .fw-series-area': { opacity: 0, pointerEvents: 'none', transition: 'opacity 160ms ease' },
  '& .fw-series-glass': { fill: 'none', strokeWidth: 13, opacity: 0, pointerEvents: 'none', transition: 'opacity 160ms ease' },
  '& .fw-series-path': { fill: 'none', strokeWidth: 2.8, transition: 'opacity 160ms ease, stroke-width 160ms ease' },
  '& .fw-series-group': { transition: 'opacity 160ms ease' },
  '& .fw-series-group:hover .fw-series-area, & .fw-series-group:focus-within .fw-series-area': { opacity: .1 },
  '& .fw-series-group:hover .fw-series-glass, & .fw-series-group:focus-within .fw-series-glass': { opacity: .13 },
  '& .fw-series-group:hover .fw-series-path, & .fw-series-group:focus-within .fw-series-path': { strokeWidth: 4, filter: 'drop-shadow(0px 7px 5px rgba(18, 37, 64, .22))' },
  '& .fw-overlay-chart:has(.fw-series-group:hover) .fw-series-group:not(:hover), & .fw-overlay-chart:has(.fw-series-group:focus-within) .fw-series-group:not(:focus-within)': { opacity: .28 },
  '& .fw-series-hit': { fill: 'none', stroke: 'transparent', strokeWidth: 20, cursor: 'pointer' },
  '& .fw-series-dot': { stroke: 'var(--fw-surface)', strokeWidth: 2 },
  '& .fw-series-point-hit': { fill: 'transparent', cursor: 'pointer' },
  '& .fw-series-legend': {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px 16px',
    marginTop: '2px',
    color: 'var(--fw-muted)',
    fontSize: '11px',
  },
  '& .fw-series-legend span': { display: 'inline-flex', alignItems: 'center', gap: '7px', padding: '5px 0', color: 'inherit' },
  '& .fw-series-swatch': { width: '14px', height: '3px', borderRadius: '2px' },
  '& .fw-in-swatch': { background: '#aeb3ff' },
  '& .fw-out-swatch': { background: '#d7d8e2' },
  '& .fw-chart-mode': { marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: '7px' },
  '& .fw-chart-mode select': { border: '1px solid var(--fw-line)', borderRadius: '5px', padding: '6px 8px', color: 'var(--fw-text)', background: 'var(--fw-surface)', fontSize: '11px' },
  '& .fw-monthly-chart': { display: 'block', width: '100%', height: 'auto', minHeight: '270px', overflow: 'visible' },
  '& .fw-monthly-chart text': { fill: 'var(--fw-muted)', fontFamily: 'var(--t-font-family)', fontSize: '10px' },
  '& .fw-monthly-grid': { stroke: 'var(--fw-line)', strokeDasharray: '2 5' },
  '& .fw-monthly-zero': { stroke: '#cfd0db', strokeWidth: 1.2 },
  '& .fw-monthly-in': { fill: '#aeb3ff', opacity: .42 },
  '& .fw-monthly-in-edge': { stroke: '#7d84ef', strokeOpacity: .58 },
  '& .fw-monthly-out': { fill: '#c8cad5', opacity: .55 },
  '& .fw-monthly-net-line': { fill: 'none', stroke: '#6269e8', strokeWidth: 2 },
  '& .fw-monthly-net-dot': { fill: '#6269e8', stroke: 'var(--fw-surface)', strokeWidth: 2 },
  '& .fw-monthly-hit': { fill: 'transparent', cursor: 'pointer' },
  '& .fw-monthly-hit:hover, & .fw-monthly-hit:focus-visible': { fill: '#f0f1ff', opacity: .65 },
  '& .fw-breakdowns': { display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: '30px', padding: '25px 0 8px' },
  '& .fw-breakdowns > div + div': { paddingLeft: '30px', borderLeft: '1px solid var(--fw-line)' },
  '& .fw-breakdown-row': { width: '100%', display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) auto auto', gap: '12px', alignItems: 'center', padding: '10px 0', border: 0, borderTop: '1px solid var(--fw-line)', color: 'var(--fw-text)', background: 'transparent', cursor: 'pointer', textAlign: 'left', fontSize: '11px' },
  '& .fw-breakdown-row small': { display: 'block', marginTop: '2px', color: 'var(--fw-muted)', fontSize: '9px' },
  '& .fw-breakdown-row strong': { fontWeight: 500, fontVariantNumeric: 'tabular-nums' },
  '& .fw-overview-foot': {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
    marginTop: '24px',
    paddingTop: '15px',
    borderTop: '1px solid var(--fw-line)',
  },
  '& .fw-workflow-actions form': {
    display: 'grid',
    gap: '12px',
    maxWidth: '700px',
    marginBottom: '24px',
  },
  '& .fw-workflow-actions label': { display: 'grid', gap: '6px' },
  '& .fw-workflow-actions input, & .fw-workflow-actions textarea, & .fw-workflow-actions select':
    {
      boxSizing: 'border-box',
      maxWidth: '100%',
      padding: '10px',
      border: '1px solid var(--fw-line)',
      borderRadius: '6px',
      background: 'var(--fw-surface)',
      color: 'var(--fw-text)',
      font: 'inherit',
    },
  '& .fw-workflow-actions textarea': { minHeight: '110px' },
  '& .fw-followup-list': {
    display: 'grid',
    marginTop: '8px',
    borderTop: '1px solid var(--fw-line)',
  },
  '& .fw-followup-row': {
    minHeight: '78px',
    display: 'grid',
    gridTemplateColumns:
      'minmax(260px, 1.7fr) minmax(120px, .7fr) minmax(120px, .7fr) minmax(220px, 1fr)',
    alignItems: 'center',
    gap: '24px',
    padding: '18px 4px',
    border: 0,
    borderBottom: '1px solid var(--fw-line)',
    color: 'var(--fw-text)',
    background: 'transparent',
    cursor: 'pointer',
    textAlign: 'left',
    transition: 'background calc(var(--t-animation-duration-fast) * 1s) ease',
  },
  '& .fw-followup-row:hover': { background: 'var(--fw-soft)' },
  '& .fw-followup-question': {
    display: 'block',
    marginBottom: '4px',
    fontSize: '14px',
    fontWeight: 600,
  },
  '& .fw-followup-meta': { color: 'var(--fw-muted)', fontSize: '10px' },
  '& .fw-followup-status': {
    display: 'inline-flex',
    width: 'fit-content',
    padding: '4px 7px',
    borderRadius: '999px',
    color: 'var(--fw-text)',
    background: 'var(--fw-nav)',
    fontSize: '10px',
  },
  '& .fw-detail-back': { marginBottom: '18px' },
  '& .fw-detail-heading': {
    maxWidth: '900px',
    marginBottom: '22px',
    paddingBottom: '20px',
    borderBottom: '1px solid var(--fw-line)',
  },
  '& .fw-detail-heading h2': {
    maxWidth: '720px',
    margin: '8px 0 12px',
    fontSize: '24px',
    fontWeight: 600,
    letterSpacing: '-.6px',
  },
  '& .fw-detail-heading .fw-page-note': { margin: '8px 0 0' },
  '& .fw-detail-tabs': {
    display: 'flex',
    gap: '5px',
    overflowX: 'auto',
    marginBottom: '24px',
    borderBottom: '1px solid var(--fw-line)',
  },
  '& .fw-detail-tab': {
    minHeight: '42px',
    flex: '0 0 auto',
    padding: '8px 12px',
    border: 0,
    borderBottom: '2px solid transparent',
    color: 'var(--fw-muted)',
    background: 'transparent',
    cursor: 'pointer',
  },
  '& .fw-detail-tab[aria-selected="true"]': {
    color: 'var(--fw-text)',
    borderBottomColor: 'var(--fw-accent)',
  },
  '& .fw-detail-section': { maxWidth: '900px' },
  '& .fw-detail-section h3': {
    margin: '26px 0 8px',
    fontSize: '13px',
    fontWeight: 650,
  },
  '& .fw-detail-list': {
    display: 'grid',
    gap: '9px',
    margin: 0,
    padding: 0,
    listStyle: 'none',
  },
  '& .fw-detail-item': {
    padding: '12px 0',
    borderBottom: '1px solid var(--fw-line)',
  },
  '& .fw-detail-item strong': { display: 'block', marginBottom: '3px' },
  '& .fw-detail-actions': {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    marginTop: '24px',
  },
  '& .fw-email-preview': {
    marginTop: '15px',
    padding: '20px',
    border: '1px solid var(--fw-line)',
    borderRadius: '8px',
    background: 'var(--fw-surface)',
  },
  '& .fw-email-body': {
    marginTop: '16px',
    paddingTop: '16px',
    borderTop: '1px solid var(--fw-line)',
    whiteSpace: 'pre-wrap',
  },
  '& .fw-shade': {
    position: 'absolute',
    inset: 0,
    zIndex: 3,
    background: 'var(--t-background-transparent-strong)',
  },
  '& .fw-drawer': {
    position: 'absolute',
    inset: '0 0 0 auto',
    zIndex: 4,
    width: 'min(430px, 100%)',
    overflowY: 'auto',
    padding: '23px',
    borderLeft: '1px solid var(--fw-line)',
    background: 'var(--fw-surface)',
    boxShadow: 'var(--t-box-shadow-strong)',
  },
  '& .fw-drawer-top': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    marginBottom: '23px',
    color: 'var(--fw-muted)',
    fontSize: '9px',
  },
  '& .fw-close': {
    border: 0,
    color: 'var(--fw-muted)',
    background: 'transparent',
    cursor: 'pointer',
    fontSize: '20px',
  },
  '& .fw-drawer-title': {
    margin: '9px 0 0',
    fontSize: '20px',
    fontWeight: 600,
    letterSpacing: '-.5px',
  },
  '& .fw-drawer-value': {
    margin: '10px 0 3px',
    fontSize: '34px',
    letterSpacing: '-1px',
    fontVariantNumeric: 'tabular-nums',
  },
  '& .fw-reason': {
    margin: '19px 0',
    padding: '12px',
    borderRadius: '6px',
    color: 'var(--fw-warn)',
    background: 'var(--fw-warn-bg)',
    fontSize: '10px',
    lineHeight: 1.5,
  },
  '& .fw-raw': {
    margin: '12px 0',
    padding: '11px',
    border: '1px solid var(--fw-line)',
    borderRadius: '5px',
    background: 'var(--fw-canvas)',
    whiteSpace: 'pre-wrap',
    overflowWrap: 'anywhere',
    font: '9px/1.7 ui-monospace, SFMono-Regular, Menlo, monospace',
  },
  '& .fw-drawer-actions': { display: 'grid', gap: '7px', marginTop: '18px' },
  '& .fw-drawer-actions .fw-button': { width: '100%', textAlign: 'center' },
  '& .fw-local': {
    marginTop: '9px',
    color: 'var(--fw-muted)',
    fontSize: '9px',
    lineHeight: 1.5,
  },
}, financeInsightsPrimitiveStyles, financeInsightsResponsiveStyles, {
  fontFamily: financeInsightsTokens.fontFamily,
  '--fw-text': financeInsightsTokens.ink, '--fw-muted': financeInsightsTokens.muted, '--fw-line': financeInsightsTokens.line,
  '--fi-frame-inline': financeInsightsTokens.frameInline,
  '--fi-content-block': financeInsightsTokens.contentBlock,
  margin: '20px auto', borderColor: financeInsightsTokens.frame,
  '&[data-view=overview]': {border: 0, borderRadius: 0, margin: 0, overflow: 'visible', background: 'transparent'},
  '&[data-view=overview] .fw-main': {padding: 0},
  '&[data-view=overview] .fw-bottom': {padding: '0 0 15px'},
  '& .fw-main': { padding: '0 0 24px' },
  '& .fw-title': {fontWeight: 500, fontSize: financeInsightsTokens.titleSize},
  '& .fw-selected-money': {fontWeight: 400, fontSize: '36px', letterSpacing: '-1.3px'},
  '& .fw-chart-stat strong': {fontWeight: 400, fontSize: '21px'},
  '& .fw-heading': {fontWeight: 500, fontSize: '16px'},
  '& .fw-recap-button strong': {fontWeight: 500, fontSize: '12px'},
  '& .fw-button': {fontSize: '12px', fontWeight: 400, minHeight: '34px', border: '1px solid #dedfe9', borderRadius: '6px', padding: '8px 12px', gap: '12px', background: '#fff', color: '#191a35'},
  '& .fw-sub, & .fw-label': {fontSize: '11px', lineHeight: 1.6},
  '& .fw-table th, & .fw-table td': {fontSize: '12px', padding: '14px 10px'},
  '& .fw-table-action': {fontWeight: 500},
  '& .fw-actions, & .fw-table-wrap, & .fw-followup-toolbar, & .fw-followup-list, & .fw-page-note, & .fw-detail-heading, & .fw-detail-tabs, & .fw-detail-section, & .fw-source-grid': { marginInline: 'var(--fi-frame-inline)' },
  '& .fw-actions': { marginTop: '2px', marginBottom: '16px' },
  '& .fi-search-input': { minHeight: '34px', padding: '8px 12px', border: `1px solid ${financeInsightsTokens.controlLine}`, borderRadius: financeInsightsTokens.controlRadius, color: 'var(--fw-text)', background: financeInsightsTokens.canvas, fontSize: financeInsightsTokens.controlSize },
  '& .fw-table-wrap': { marginTop: '4px' },
  '& .fw-table': { fontSize: financeInsightsTokens.detailSize },
  '& .fw-table th': { padding: '11px 10px', color: 'var(--fw-muted)', background: financeInsightsTokens.canvas, fontSize: financeInsightsTokens.detailSize, fontWeight: 400 },
  '& .fw-table td': { height: '48px', padding: '11px 10px' },
  '& .fw-followup-toolbar': { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '12px', marginBottom: '8px' },
  '& .fw-followup-toolbar .fw-page-note': { margin: 0 },
  '& .fw-followup-list': { marginTop: 0 },
  '& .fw-followup-row': { minHeight: '70px', padding: '14px 0', gap: '18px' },
  '& .fw-followup-question': { fontSize: '12px', fontWeight: 500 },
  '& .fw-page-note': { marginTop: 0, marginBottom: '16px', color: 'var(--fw-muted)', fontSize: financeInsightsTokens.detailSize },
  '& .fw-detail-heading': { marginTop: '4px' },
  '& .fw-bottom': { margin: `0 var(--fi-frame-inline)`, paddingTop: '16px' },
  '& .fw-scope-toolbar': {display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: '12px', margin: '24px 0 6px'},
  '& .fw-filter-popover': {position: 'relative', flexShrink: 0},
  '& .fw-filter-popover summary': {listStyle: 'none', display: 'flex', gap: '14px', alignItems: 'center', cursor: 'pointer'},
  '& .fw-filter-popover summary::-webkit-details-marker': {display: 'none'},
  '& .fw-filter-body': {position: 'absolute', top: '42px', left: 0, padding: '16px', zIndex: 10, background: 'var(--fw-surface)', border: '1px solid var(--fw-line)', borderRadius: '7px', boxShadow: '0 8px 20px #20213a12'},
  '& .fw-filter-body label': {display: 'grid', gap: '8px', fontSize: '12px'},
  '& .fw-date-popover': {left: 'auto', right: 0, zIndex: 10, minWidth: 0, width: '300px', maxWidth: 'calc(100vw - 56px)'},
  '& .fw-insights-layout': {gridTemplateColumns: '28% minmax(0,1fr)', margin: 0, padding: '28px 0', borderBottom: '1px solid var(--fw-line)'},
  '& .fw-monthly-in': {fill: 'url(#fw-in-fill)', opacity: 1},
  '& .fw-monthly-out': {fill: 'url(#fw-out-fill)', opacity: 1},
  '& .fw-monthly-hit:hover, & .fw-monthly-hit:focus-visible': {fill: 'var(--fw-accent)', opacity: .045},
  '& .fw-comparison': {display: 'grid', gap: '5px', marginTop: '20px', color: 'var(--fw-muted)', fontSize: '12px'},
  '& .fw-comparison strong': {fontWeight: 500, color: 'var(--fw-text)'},
  '& .fw-section-head': {display: 'flex', justifyContent: 'space-between', gap: '16px', margin: '20px 0'},
  '& .fw-drill .fw-breakdown-row': {fontSize: '12px'},
  '@media (max-width: 850px)': {
    '& .fw-layout': { gridTemplateColumns: '136px minmax(0, 1fr)' },
    '& .fw-main': { padding: '20px 17px' },
    '& .fw-overview': { gridTemplateColumns: '1fr' },
    '& .fw-attention': { paddingLeft: 0, borderLeft: 0 },
    '& .fw-value': { fontSize: '25px' },
    '& .fw-account-col': { display: 'none' },
    '& .fw-insights-layout': { gridTemplateColumns: '1fr' },
    '& .fw-narrative-panel': { padding: '0 0 22px', borderRight: 0, borderBottom: '1px solid var(--fw-line)' },
    '& .fw-movement-hero': { padding: '24px 0 0' },
    '& .fw-followup-row': {
      gridTemplateColumns:
        'minmax(220px, 1.5fr) minmax(110px, .7fr) minmax(180px, 1fr)',
    },
    '& .fw-followup-owner': { display: 'none' },
  },
  '@media (max-width: 580px)': {
    minHeight: 0,
    '& .fw-layout': { display: 'block' },
    '& .fw-nav': {
      flexDirection: 'row',
      overflowX: 'auto',
      padding: '7px',
      borderRight: 0,
      borderBottom: '1px solid var(--fw-line)',
    },
    '& .fw-nav-label, & .fw-nav-meta, & .fw-nav-glyph': { display: 'none' },
    '& .fw-nav-button': {
      width: 'auto',
      flex: '0 0 auto',
      minHeight: '44px',
      padding: '9px',
    },
    '& .fw-main': { padding: '17px 14px' },
    '& .fw-select': {
      minHeight: '44px',
      flex: 1,
      minWidth: 0,
      maxWidth: 'none',
      fontSize: '16px',
    },
    '& .fw-metrics': { gridTemplateColumns: '1.15fr .85fr 1fr', gap: '9px' },
    '& .fw-value': { fontSize: '21px' },
    '& .fw-value small': { display: 'block', fontSize: '9px' },
    '& .fw-chart': {
      gridTemplateColumns: '28px repeat(2, minmax(62px, 1fr))',
      gap: '7px',
    },
    '& .fw-panels': { gridTemplateColumns: '1fr' },
    '& .fw-date-col, & .fw-date-cell, & .fw-account-col, & .fw-account-cell': {
      display: 'none',
    },
    '& .fw-evidence-col': { width: '28%' },
    '& .fw-money-col': { width: '22%' },
    '& .fw-actions': { flexWrap: 'wrap' },
    '& .fw-account-picker': { marginLeft: 0, minWidth: 0, width: '100%' },
    '& .fw-bottom': { flexWrap: 'wrap' },
    '& .fw-drawer': { padding: '19px' },
    '& .fw-date-input': {
      minHeight: '44px',
      minWidth: 0,
      width: '100%',
      fontSize: '16px',
    },
    '& .fw-window-handle': { width: '44px', marginLeft: '-22px' },
    '& .fw-month-labels span:nth-of-type(even)': { visibility: 'hidden' },
    '& .fw-insights-layout': { display: 'flex', flexDirection: 'column' },
    '& .fw-recap': {
      gridTemplateColumns: '1fr',
      gap: '14px',
      marginTop: '15px',
    },
    '& .fw-line-chart': { height: '230px' },
    '& .fw-movement-hero': { padding: '16px 0 13px' },
    '& .fw-movement-head': { display: 'block' },
    '& .fw-chart-viewport .fw-overlay-chart': { minWidth: '720px' },
    '& .fw-followup-row': {
      minHeight: 'auto',
      gridTemplateColumns: '1fr',
      gap: '8px',
      padding: '17px 2px',
    },
    '& .fw-followup-owner': { display: 'block' },
    '& .fw-email-preview': { padding: '15px' },
  },
  '@media (pointer: coarse)': {
    '& .fw-window-handle': { width: '44px', marginLeft: '-22px' },
  },
  '@media (prefers-reduced-motion: reduce)': {
    '& *': { transition: 'none !important' },
  },
});
